stages:
  - build
  - test

variables:
  PROJECT_NAME: 业务名称
  REPO_NAME: python
  IMAGE_TAG: ${CI_COMMIT_SHA}
  TESTING_IMAGE: ${DOCKER_SERVER}/${PROJECT_NAME}/${REPO_NAME}:v0.0.1

build:
  stage: build
  image: docker:stable
  script:
  - echo "Building"
  - chmod 777 -R tests/
  - docker version
  - docker build -t ${TESTING_IMAGE} .
  - docker login -u $HUB_DEV_USERNAME -p $HUB_DEV_PASSWORD $HUB_DEV_ADDR
  - docker push ${TESTING_IMAGE}
  only:
  - develop

test:
  image: ${TESTING_IMAGE}
  stage: test
  script:
  - echo "Testing"
  - chmod 777 -R tests/
  - nose2
  - coverage report -m
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
  only:
  - develop
  when: always